### PR TITLE
Add passthrough for derived tables

### PR DESCRIPTION
**Pull request by rlh1994**
## Description & motivation
Add passthrough values for the page views, sessions, and users derived tables. These can be provided in one of two ways, either as a string which just brings the column through as is, or via custom sql (which then requires an alias) provided in a dictionary.

Page views takes the value from the page view event itself, Sessions takes it from the first page view or page ping event, and users takes it from the sessions table for the first or last session for that user. 

I have also added the ability to provide a different field for user stitching so that if someone did not track userID correctly they could use a field from a context (assuming they provide the sql to extract it).

Readme and docs updates will be done as part of the release, once Utils has a RC ready to point to.

## Checklist
- [x] I have verified that these changes work locally
- [ ] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have raised a [documentation](https://github.com/snowplow/documentation) PR if applicable (Link here if required)
- [ ] Is your change a breaking change?

### CODE REVIEW

**Comment by m-feeser** [comment]
If I'm understanding correctly, this would feature would allow for columns or for attributes embedded within columns from the base event table to propagate to the final derived page_views and session derived tables. Is that right?

For my use case, I'm looking to get values from global contexts from the base event onto the derived page views and would like to not have to write a full custom model to do it. Would this proposed feature work for that use case?

Do you have a timeline for when this will be released?

**Comment by rlh1994** [comment]
Hi @m-feeser 

>Is that right?
Yes the idea is to pass any columns through from the base events this run to page views, sessions and users, although these will be from the page view/first page view or ping events respectively rather than allow any form of aggregation.

>Do you have a timeline for when this will be released?
We're currently aiming for a Release candidate by the end of August (as this depends on a snowplow utils RC as well), then assuming no big issues a full release by the end of September. It may be sooner but those are our current timelines.

**Comment by m-feeser** [comment]
> Hi @m-feeser
> 
> > Is that right?
> 
> Yes the idea is to pass any columns through from the base events this run to page views, sessions and users, although these will be from the page view/first page view or ping events respectively rather than allow any form of aggregation.
> 
> > Do you have a timeline for when this will be released?
> 
> We're currently aiming for a Release candidate by the end of August (as this depends on a snowplow utils RC as well), then assuming no big issues a full release by the end of September. It may be sooner but those are our current timelines.

Thanks for the response. Looking forward to seeing this released and using it.

**Review by agnessnowplow — APPROVED** [review]
Nice and clean, nothing to add apart from the comments! I could only break it by adding the same field twice but that would be an overkill to add as safety measure.

**Pull request merged**
