### PR TITLE
Release/snowplow-web/0.5.0

### PR DESCRIPTION
**Pull request by bill-warner**
Running through Redshift tests. Will confirm results

### CODE REVIEW

**Review by paulboocock — APPROVED** [review]
LGTM assuming your Redshift tests went ok and the temp commit is removed 👍

**Comment by bill-warner** [comment]
For clarity I am holding off merging this as although all tests pass on Redshift, dbt is throwing warnings for the optional page view context models such as:

```bash
[WARNING]: Test 'test.snowplow_web.not_null_snowplow_web_pv_iab_page_view_id.858bd03daa' (models/page_views/scratch/page_views_scratch.yml) depends on a node named 'snowplow_web_pv_iab' which is disabled
```

This is because the model `snowplow_web_pv_iab` is [disabled by default](https://github.com/snowplow/dbt-snowplow-web/blob/fadda799f9fa96eb890d98f66f5031fbba6ff12d/models/page_views/scratch/default/snowplow_web_pv_iab.sql#L5) using the `snowplow__enable_iab` var but the tests are not. 

These page view context models are only to be run on Redshift and Postgres and as such I have set the tests to only run for these databases:
https://github.com/snowplow/dbt-snowplow-web/blob/fadda799f9fa96eb890d98f66f5031fbba6ff12d/models/page_views/scratch/page_views_scratch.yml#L261-L264

I have tried disabling the test if the model is also disabled like beneath but unfortunately the vars value doesnt seem to be being read in from the `dbt_project.yml` file where [it is set.](https://github.com/snowplow/dbt-snowplow-web/blob/eefeb63082bb2e6d12c0717b90c8d4a3d005dfc5/dbt_project.yml#L36-L38) 
```yml
- unique:
     enabled: "{{ var('snowplow__enable_iab') and target.type in ['redshift', 'postgres'] | as_bool() }}"
```
I have reached out to dbt for help

**Comment by bill-warner** [comment]
I think the issue I outlined above has been raised already:
https://github.com/dbt-labs/dbt-core/issues/3698

Added my example in the hope of speeding up the fix. I think I have a workaround - will add now.

**Comment by bill-warner** [comment]
All tests for Redshift have passed locally. @paulboocock - will fix up latest commit and merge PR once you have cast your eye over the fix.

**Review by paulboocock — APPROVED** [review]
Thats a fun little bug. The fix looks good to me though.

**Pull request merged**
